# Site settings
author: Wheeler
title: ProvesTheRuleException
header-img: img/home-bg.png
email: wheeler.pryor@gmail.com
copyright_name: Wheeler
description: > # this means to ignore newlines until "baseurl:"
  a technical blog (but you knew that already)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wingedmachine

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
